/**
 * Activity Log Models & Schemas
 */

export const ACTIVITY_TYPES = {
  ADMIN_LOGIN: 'Admin Login',
  ADMIN_LOGOUT: 'Admin Logout',
  BOOK_ADDED: 'Book Added',
  BOOK_EDITED: 'Book Edited',
  BOOK_ARCHIVED: 'Book Archived',
  BOOK_RESTORED: 'Book Restored',
  BOOK_DELETED: 'Book Deleted',
  BORROW_APPROVED: 'Borrow Request Approved',
  BORROW_REJECTED: 'Borrow Request Rejected',
  BOOK_ISSUED: 'Book Issued',
  BOOK_RETURNED: 'Book Returned',
  QR_GENERATED: 'QR Code Generated',
  STUDENT_UPDATED: 'Student Record Updated',
  NOTIFICATION_SENT: 'Notification Sent',
  ANNOUNCEMENT_PUBLISHED: 'Announcement Published',
  SETTINGS_CHANGED: 'Settings Changed',
  ROLE_UPDATED: 'Role Updated',
};

export const MODULE_TYPES = {
  AUTH: 'Authentication',
  BOOKS: 'Book Management',
  REQUESTS: 'Borrow Requests',
  RETURNS: 'Issue & Returns',
  STUDENTS: 'Student Directory',
  SCANNER: 'QR & Barcode Scanner',
  NOTIFICATIONS: 'Notifications & Announcements',
  ANALYTICS: 'Reports & Analytics',
  SETTINGS: 'Settings & Security',
};

/**
 * Initial Seed Activity Log Dataset
 */
export const INITIAL_MOCK_ACTIVITIES = [
  {
    id: 'LOG-2024-901',
    activityId: 'LOG-2024-901',
    activityType: ACTIVITY_TYPES.BOOK_ISSUED,
    module: MODULE_TYPES.RETURNS,
    performedBy: 'Lead Librarian Admin',
    adminEmail: 'admin@borrow.com',
    affectedDocumentId: 'CPY-235088-001',
    affectedDocumentName: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    oldData: { status: 'Available' },
    newData: { status: 'Borrowed', borrower: 'Marcus Vance (2023-CS-019)', dueDate: '2024-08-04' },
    status: 'Success',
    ipAddress: '192.168.1.45',
    device: 'Chrome / Windows 11 Desktop',
    createdAt: new Date('2024-07-22T10:30:00').toISOString(),
  },
  {
    id: 'LOG-2024-902',
    activityId: 'LOG-2024-902',
    activityType: ACTIVITY_TYPES.BORROW_APPROVED,
    module: MODULE_TYPES.REQUESTS,
    performedBy: 'Lead Librarian Admin',
    adminEmail: 'admin@borrow.com',
    affectedDocumentId: 'REQ-2024-1048',
    affectedDocumentName: 'Clean Code (Alex Rivera)',
    oldData: { status: 'Pending' },
    newData: { status: 'Approved', loanPeriodDays: 14 },
    status: 'Success',
    ipAddress: '192.168.1.45',
    device: 'Chrome / Windows 11 Desktop',
    createdAt: new Date('2024-07-22T09:15:00').toISOString(),
  },
  {
    id: 'LOG-2024-903',
    activityId: 'LOG-2024-903',
    activityType: ACTIVITY_TYPES.BOOK_ADDED,
    module: MODULE_TYPES.BOOKS,
    performedBy: 'Lead Librarian Admin',
    adminEmail: 'admin@borrow.com',
    affectedDocumentId: 'BOOK-9780132350884',
    affectedDocumentName: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    oldData: null,
    newData: { title: 'Clean Code', copies: 5, category: 'Software Engineering' },
    status: 'Success',
    ipAddress: '192.168.1.45',
    device: 'Chrome / Windows 11 Desktop',
    createdAt: new Date('2024-07-21T14:00:00').toISOString(),
  },
  {
    id: 'LOG-2024-904',
    activityId: 'LOG-2024-904',
    activityType: ACTIVITY_TYPES.NOTIFICATION_SENT,
    module: MODULE_TYPES.NOTIFICATIONS,
    performedBy: 'Lead Librarian Admin',
    adminEmail: 'admin@borrow.com',
    affectedDocumentId: 'NOTIF-2024-001',
    affectedDocumentName: 'New Computer Science Textbooks Available',
    oldData: null,
    newData: { target: 'All Students', priority: 'Normal' },
    status: 'Success',
    ipAddress: '192.168.1.45',
    device: 'Chrome / Windows 11 Desktop',
    createdAt: new Date('2024-07-21T11:00:00').toISOString(),
  },
  {
    id: 'LOG-2024-905',
    activityId: 'LOG-2024-905',
    activityType: ACTIVITY_TYPES.ADMIN_LOGIN,
    module: MODULE_TYPES.AUTH,
    performedBy: 'Lead Librarian Admin',
    adminEmail: 'admin@borrow.com',
    affectedDocumentId: 'AUTH-SESSION-884',
    affectedDocumentName: 'Lead Librarian Session',
    oldData: null,
    newData: { role: 'Admin' },
    status: 'Success',
    ipAddress: '192.168.1.45',
    device: 'Chrome / Windows 11 Desktop',
    createdAt: new Date('2024-07-21T08:00:00').toISOString(),
  },
];
